// next-sitemap.config.js
module.exports = {
  siteUrl: "https://www.thesmartlines.com",
  generateRobotsTxt: false,
  sitemapSize: 5000,
  exclude: [
    "/account",
    "/api",
    "/arbitrage",
    "/arbitrage-opportunities",
    "/checkout",
    "/contexts",
    "/expected-value",
    "/login",
    "/money-line-MLB",
    "/money-line-NBA",
    "/money-line-NFL",
    "/money-line-NHL",
    "/over-under-MLB",
    "/over-under-NBA",
    "/over-under-NFL",
    "/over-under-NHL",
    "/player-props-MLB",
    "/player-props-NBA",
    "/player-props-NFL",
    "/player-props-NHL",
    "/spreads-MLB",
    "/spreads-NBA",
    "/spreads-NFL",
    "/spreads-NHL",
    "/password-reset",
    "/password-reset-confirm",
    "/register",
    "/success",
    "/verify-email",
  ],
};
