# Generated by Django 4.2.16 on 2025-01-04 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='latest_Moneyline',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('bookie', models.TextField()),
                ('matchup_type', models.TextField()),
                ('home_team', models.TextField()),
                ('line_1', models.BigIntegerField()),
                ('away_team', models.TextField()),
                ('line_2', models.BigIntegerField()),
                ('event_timestamp', models.DateTimeField()),
                ('last_updated_timestamp', models.DateTimeField()),
                ('sport_type', models.TextField()),
            ],
            options={
                'db_table': 'latest_moneyline',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='latest_Overunder',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('bookie', models.TextField()),
                ('matchup_type', models.TextField()),
                ('home_team', models.TextField()),
                ('away_team', models.TextField()),
                ('over_or_under_1', models.TextField()),
                ('over_under_total_1', models.FloatField()),
                ('over_under_line_1', models.BigIntegerField()),
                ('over_or_under_2', models.TextField()),
                ('over_under_total_2', models.FloatField()),
                ('over_under_line_2', models.BigIntegerField()),
                ('event_timestamp', models.DateTimeField()),
                ('last_updated_timestamp', models.DateTimeField()),
                ('sport_type', models.TextField()),
            ],
            options={
                'db_table': 'latest_overunder',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='latest_Props',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('last_updated_timestamp', models.DateTimeField()),
                ('bookie', models.TextField()),
                ('prop_type', models.TextField()),
                ('bet_type', models.TextField()),
                ('player_name', models.TextField()),
                ('betting_line', models.BigIntegerField()),
                ('betting_point', models.TextField()),
                ('sport_type', models.TextField()),
            ],
            options={
                'db_table': 'latest_props',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='latest_Spreads',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('bookie', models.TextField()),
                ('matchup_type', models.TextField()),
                ('home_team', models.TextField()),
                ('spread_1', models.FloatField()),
                ('line_1', models.BigIntegerField()),
                ('away_team', models.TextField()),
                ('spread_2', models.FloatField()),
                ('line_2', models.BigIntegerField()),
                ('event_timestamp', models.DateTimeField()),
                ('last_updated_timestamp', models.DateTimeField()),
                ('sport_type', models.TextField()),
            ],
            options={
                'db_table': 'latest_spreads',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DistinctProps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=255)),
                ('game_ID', models.CharField(max_length=255)),
                ('sport_type', models.CharField(max_length=255)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('player_name', 'game_ID', 'sport_type')},
            },
        ),
    ]
