# Generated by Django 4.2.16 on 2025-01-05 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0002_latest_moneyline_latest_overunder_latest_props_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distinctprops',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        # migrations.AlterModelTable(
        #     name='distinctprops',
        #     table='distinct_props',
        # ),
    ]
