# Generated by Django 4.2.16 on 2025-01-05 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0003_alter_distinctprops_id_alter_distinctprops_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='distinctprops',
            old_name='game_ID',
            new_name='game_id',
        ),
        migrations.AlterUniqueTogether(
            name='distinctprops',
            unique_together={('player_name', 'game_id', 'sport_type')},
        ),
        migrations.AlterModelTable(
            name='distinctprops',
            table='distinct_props',
        ),
    ]
