# Generated by Django 4.2.16 on 2025-02-04 18:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0005_usersubscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersubscription',
            name='start_date',
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='trial_start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='status',
            field=models.CharField(default='trial', max_length=50),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
