# Generated by Django 4.2.16 on 2025-02-09 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0006_remove_usersubscription_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
