# Generated by Django 4.2.19 on 2025-03-07 20:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sports', '0007_usersubscription_stripe_customer_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.IntegerField()),
                ('bookie', models.CharField(max_length=50)),
                ('bet_type', models.CharField(choices=[('moneyline', 'Moneyline'), ('spread', 'Spread'), ('total', 'Total')], max_length=20)),
                ('line', models.FloatField()),
                ('alert_threshold', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'userbet',
            },
        ),
    ]
