# Generated by Django 4.2.19 on 2025-03-10 18:26

from django.db import migrations, models

def convert_game_id_to_uuid(apps, schema_editor):
    # Drop the old `game_id` column
    schema_editor.execute("""
        ALTER TABLE userbet DROP COLUMN game_id;
    """)

    # Add the new `game_id` column as UUID
    schema_editor.execute("""
        ALTER TABLE userbet ADD COLUMN game_id UUID;
    """)

class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0008_userbet'),
    ]

    operations = [
        migrations.RunPython(convert_game_id_to_uuid, atomic=False),  # Disable atomicity for this operation
    ]
