# Generated by Django 4.2.19 on 2025-03-10 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0009_alter_userbet_game_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbet',
            name='game_id',
        ),
        migrations.AddField(
            model_name='userbet',
            name='game',
            field=models.ForeignKey(blank=True, db_column='game_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sports.scores', to_field='game_id'),
        ),
    ]
