# Generated by Django 4.2.19 on 2025-03-10 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0010_remove_userbet_game_id_userbet_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbet',
            name='team_bet_on',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userbet',
            name='bet_type',
            field=models.CharField(choices=[('moneyline', 'Moneyline')], max_length=20),
        ),
    ]
