# Generated by Django 4.2.19 on 2025-03-11 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0011_userbet_team_bet_on_alter_userbet_bet_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbet',
            name='bet_amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=15),
            preserve_default=False,
        ),
    ]
